"""preferencie pouzivatela

Revision ID: 0e8b0cc5b4de
Revises: 40b3ef51a866
Create Date: 2026-09-26 19:52:47.396230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8b0cc5b4de'
down_revision: Union[str, Sequence[str], None] = '40b3ef51a866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Existujúce účty dostanú prázdne nastavenia, inak by NOT NULL zlyhalo.
        batch_op.add_column(
            sa.Column('preferences', sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
