"""licencne cista viditelnost

Údaje z Brickset a BrickEconomy sa presunú z catalog_items do vlastných
tabuliek. Kto ich smie vidieť, určí source_access; prístupy sa naplnia pri
štarte appky (services/access_backfill.py), lebo potrebujú odtlačky kľúčov
a tie sa dajú zistiť len rozšifrovaním (JWT_SECRET), nie v migrácii.

Revision ID: 155aeaebee97
Revises: f210297cdb24
Create Date: 2026-09-28 07:58:22.294113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '155aeaebee97'
down_revision: Union[str, Sequence[str], None] = 'f210297cdb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_access')),
    sa.UniqueConstraint('provider', 'fingerprint', 'subject', name='uq_source_access')
    )
    with op.batch_alter_table('source_access', schema=None) as batch_op:
        batch_op.create_index('ix_source_access_fingerprint', ['fingerprint', 'provider'], unique=False)

    op.create_table('brickeconomy_facts',
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('subtheme', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('num_minifigs', sa.Integer(), nullable=True),
    sa.Column('rrp_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.Integer(), nullable=True),
    sa.Column('retired_date', sa.Date(), nullable=True),
    sa.Column('minifig_no', sa.String(length=64), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('forecast_2y_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forecast_5y_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('growth_12m_pct', sa.Float(), nullable=True),
    sa.Column('growth_last_year_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_brickeconomy_facts_catalog_num_catalog_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('catalog_num', name=op.f('pk_brickeconomy_facts'))
    )
    with op.batch_alter_table('brickeconomy_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brickeconomy_facts_ean'), ['ean'], unique=False)

    op.create_table('brickset_facts',
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('num_minifigs', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('rrp_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.Integer(), nullable=True),
    sa.Column('ean', sa.String(length=14), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('owned_by', sa.Integer(), nullable=True),
    sa.Column('wanted_by', sa.Integer(), nullable=True),
    sa.Column('brickset_id', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('extended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_brickset_facts_catalog_num_catalog_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('catalog_num', name=op.f('pk_brickset_facts'))
    )
    with op.batch_alter_table('brickset_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brickset_facts_ean'), ['ean'], unique=False)

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ean_source', sa.String(length=16), nullable=True))

    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_price_snapshots_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    _move_data()

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_column('growth_last_year_pct')
        batch_op.drop_column('forecast_5y_eur')
        batch_op.drop_column('bs_image_count')
        batch_op.drop_column('bs_owned_by')
        batch_op.drop_column('brickset_checked_at')
        batch_op.drop_column('growth_12m_pct')
        batch_op.drop_column('forecast_2y_eur')
        batch_op.drop_column('minifig_no')
        batch_op.drop_column('bs_rating')
        batch_op.drop_column('bs_rating_count')
        batch_op.drop_column('bs_wanted_by')
        batch_op.drop_column('subtheme')
        batch_op.drop_column('brickset_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('description')
        batch_op.drop_column('retired_date')
        batch_op.drop_column('bs_images')

    # ### end Alembic commands ###


def _move_data() -> None:
    """Presun existujúcich údajov; nič sa nestratí, len sa rozdelí podľa zdroja."""
    # Brickset: všetko, na čo sa Brickset pýtal, aj sety len z vĺn.
    op.execute("""
        INSERT INTO brickset_facts (catalog_num, found, name, year, theme, num_parts,
            num_minifigs, image_url, rrp_eur, is_retired, retired_at, ean, description, tags,
            rating, rating_count, owned_by, wanted_by, brickset_id, image_count, images,
            extended_at, fetched_at)
        SELECT catalog_num,
            CASE WHEN description IS NOT NULL OR tags IS NOT NULL OR bs_rating IS NOT NULL
                OR bs_owned_by IS NOT NULL OR brickset_id IS NOT NULL
                OR source LIKE '%brickset%' THEN 1 ELSE 0 END,
            name, year, theme, num_parts, num_minifigs, image_url, rrp_eur, is_retired,
            retired_at, ean, description, tags, bs_rating, bs_rating_count, bs_owned_by,
            bs_wanted_by, brickset_id, bs_image_count, bs_images,
            brickset_checked_at, COALESCE(brickset_checked_at, fetched_at)
        FROM catalog_items
        WHERE brickset_checked_at IS NOT NULL OR source LIKE '%brickset%'
    """)
    # BrickEconomy: odhady a ďalšie údaje z odpovede o cene, aj sety s cenou.
    op.execute("""
        INSERT INTO brickeconomy_facts (catalog_num, name, theme, subtheme, year, num_parts,
            num_minifigs, rrp_eur, is_retired, retired_at, retired_date, minifig_no, ean,
            forecast_2y_eur, forecast_5y_eur, growth_12m_pct, growth_last_year_pct,
            fetched_at)
        SELECT c.catalog_num,
            CASE WHEN c.source = 'brickeconomy' THEN c.name END,
            CASE WHEN c.source = 'brickeconomy' THEN c.theme END,
            c.subtheme,
            CASE WHEN c.source = 'brickeconomy' THEN c.year END,
            CASE WHEN c.source = 'brickeconomy' THEN c.num_parts END,
            CASE WHEN c.source = 'brickeconomy' THEN c.num_minifigs END,
            CASE WHEN c.brickset_checked_at IS NULL AND c.source NOT LIKE '%brickset%'
                THEN c.rrp_eur END,
            CASE WHEN c.brickset_checked_at IS NULL AND c.source NOT LIKE '%brickset%'
                THEN c.is_retired ELSE 0 END,
            CASE WHEN c.brickset_checked_at IS NULL AND c.source NOT LIKE '%brickset%'
                THEN c.retired_at END,
            c.retired_date, c.minifig_no,
            CASE WHEN c.brickset_checked_at IS NULL AND c.source NOT LIKE '%brickset%'
                THEN c.ean END,
            c.forecast_2y_eur, c.forecast_5y_eur, c.growth_12m_pct,
            c.growth_last_year_pct, c.fetched_at
        FROM catalog_items c
        WHERE c.source = 'brickeconomy' OR c.subtheme IS NOT NULL
            OR c.minifig_no IS NOT NULL OR c.retired_date IS NOT NULL
            OR c.forecast_2y_eur IS NOT NULL OR c.growth_12m_pct IS NOT NULL
            OR EXISTS (SELECT 1 FROM price_snapshots p
                       WHERE p.catalog_num = c.catalog_num AND p.source != 'manual')
    """)
    # Spoločný katalóg: RRP a retired prišli z Brickset alebo BE, sú teraz vo
    # facts. Ručne založené sety ich majú od používateľa, tie ostávajú.
    op.execute("""
        UPDATE catalog_items SET rrp_eur = NULL, is_retired = 0, retired_at = NULL
        WHERE source != 'manual'
    """)
    # Počet figúrok Rebrickable neposiela, bol z Brickset; fotka z Brickset tiež.
    op.execute("""
        UPDATE catalog_items SET num_minifigs = NULL
        WHERE source != 'manual' AND num_minifigs IS NOT NULL
    """)
    op.execute("""
        UPDATE catalog_items SET image_url = NULL
        WHERE source != 'manual' AND image_url LIKE '%images.brickset.com%'
    """)
    # Kód, ktorý má aj Brickset alebo BE, patrí do ich facts, nie všetkým.
    op.execute("""
        UPDATE catalog_items SET ean = NULL
        WHERE ean IS NOT NULL AND source != 'manual' AND (
            EXISTS (SELECT 1 FROM brickset_facts b
                    WHERE b.catalog_num = catalog_items.catalog_num AND b.ean = catalog_items.ean)
            OR EXISTS (SELECT 1 FROM brickeconomy_facts e
                    WHERE e.catalog_num = catalog_items.catalog_num AND e.ean = catalog_items.ean))
    """)
    # Zvyšné kódy: pôvod nepoznáme, berú sa ako z UPCitemdb (spec).
    op.execute("UPDATE catalog_items SET ean_source = 'upcitemdb' WHERE ean IS NOT NULL")
    # Sety len z Brickset (vlny) alebo BrickEconomy (Overiť cenu): v katalógu len číslo.
    op.execute("""
        UPDATE catalog_items SET name = 'Set ' || catalog_num, year = NULL, theme = NULL,
            num_parts = NULL, num_minifigs = NULL, image_url = NULL
        WHERE source IN ('brickset', 'brickeconomy')
    """)
    # Ručné ceny patria majiteľovi setu; pri viacerých majiteľoch má každý kópiu.
    owners = """
        SELECT catalog_num, user_id FROM collection_items
        UNION SELECT catalog_num, user_id FROM wishlist_items
        UNION SELECT catalog_num, user_id FROM price_checks
    """
    op.execute(f"""
        UPDATE price_snapshots SET user_id = (
            SELECT MIN(o.user_id) FROM ({owners}) o
            WHERE o.catalog_num = price_snapshots.catalog_num)
        WHERE source = 'manual'
    """)
    op.execute(f"""
        INSERT INTO price_snapshots (catalog_num, source, price_kind, condition, avg_price,
            min_price, max_price, qty, currency, captured_at, user_id)
        SELECT p.catalog_num, p.source, p.price_kind, p.condition, p.avg_price, p.min_price,
            p.max_price, p.qty, p.currency, p.captured_at, o.user_id
        FROM price_snapshots p
        JOIN ({owners}) o
            ON o.catalog_num = p.catalog_num
        WHERE p.source = 'manual' AND o.user_id != p.user_id
    """)
    # Existujúce účty: UPCitemdb a Eurostat ostanú zapnuté ako doteraz;
    # predvolene vypnuté sú len pre nové účty.
    op.execute("""
        UPDATE users SET fetch_settings = json_set(COALESCE(NULLIF(fetch_settings, 'null'), '{}'),
            '$.enabled', json('["eurostat.inflation", "upcitemdb.barcode"]'))
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Návrat späť vráti stĺpce, ale nie ich obsah (ten je vo facts).
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_price_snapshots_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bs_images', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('retired_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('tags', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('brickset_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subtheme', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('bs_wanted_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bs_rating_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bs_rating', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('minifig_no', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('forecast_2y_eur', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('growth_12m_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('brickset_checked_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('bs_owned_by', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bs_image_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('forecast_5y_eur', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('growth_last_year_pct', sa.FLOAT(), nullable=True))
        batch_op.drop_column('ean_source')

    with op.batch_alter_table('brickset_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brickset_facts_ean'))

    op.drop_table('brickset_facts')
    with op.batch_alter_table('brickeconomy_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brickeconomy_facts_ean'))

    op.drop_table('brickeconomy_facts')
    with op.batch_alter_table('source_access', schema=None) as batch_op:
        batch_op.drop_index('ix_source_access_fingerprint')

    op.drop_table('source_access')
    # ### end Alembic commands ###
