"""brickset popis a hodnotenie

Revision ID: 1eec9d8ecb2e
Revises: ea581ebbda0d
Create Date: 2026-09-26 21:40:23.228831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eec9d8ecb2e'
down_revision: Union[str, Sequence[str], None] = 'ea581ebbda0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bs_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bs_rating_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bs_owned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bs_wanted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brickset_checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_column('brickset_checked_at')
        batch_op.drop_column('bs_wanted_by')
        batch_op.drop_column('bs_owned_by')
        batch_op.drop_column('bs_rating_count')
        batch_op.drop_column('bs_rating')
        batch_op.drop_column('tags')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
