"""ciarovy kod setu

Revision ID: 40b3ef51a866
Revises: e80577154902
Create Date: 2026-09-26 16:52:11.964166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b3ef51a866'
down_revision: Union[str, Sequence[str], None] = 'e80577154902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ean', sa.String(length=14), nullable=True))
        batch_op.create_index('ix_catalog_items_ean', ['ean'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_items_ean')
        batch_op.drop_column('ean')

    # ### end Alembic commands ###
