"""vlny tem

Revision ID: 41f471e813d2
Revises: 1eec9d8ecb2e
Create Date: 2026-09-26 21:54:06.000834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f471e813d2'
down_revision: Union[str, Sequence[str], None] = '1eec9d8ecb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_waves',
    sa.Column('theme', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('set_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('theme', 'year', name=op.f('pk_theme_waves'))
    )
    op.create_table('theme_wave_sets',
    sa.Column('theme', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_theme_wave_sets_catalog_num_catalog_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theme', 'year', 'catalog_num', name=op.f('pk_theme_wave_sets'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_wave_sets')
    op.drop_table('theme_waves')
    # ### end Alembic commands ###
