"""krabica pri umiestneni

Revision ID: 421dd563c685
Revises: c6ca75a14f1e
Create Date: 2026-09-27 18:07:53.621846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421dd563c685'
down_revision: Union[str, Sequence[str], None] = 'c6ca75a14f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_column('box')

    # ### end Alembic commands ###
