"""zoznamy, fotky, poplatky, podtema

Revision ID: 57764f8fc05e
Revises: c30e390ab49a
Create Date: 2026-09-26 13:50:21.430926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57764f8fc05e'
down_revision: Union[str, Sequence[str], None] = 'c30e390ab49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['collection_items.id'], name=op.f('fk_item_photos_item_id_collection_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_item_photos_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_photos'))
    )
    with op.batch_alter_table('item_photos', schema=None) as batch_op:
        batch_op.create_index('ix_item_photos_item_id', ['item_id'], unique=False)

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtheme', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('retired_date', sa.Date(), nullable=True))

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_fees_eur', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sold_shipping_eur', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_collection_items_purpose'), ['purpose'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_purpose'))
        batch_op.drop_column('purpose')
        batch_op.drop_column('sold_shipping_eur')
        batch_op.drop_column('sold_fees_eur')

    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_column('retired_date')
        batch_op.drop_column('subtheme')

    with op.batch_alter_table('item_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_item_photos_item_id')

    op.drop_table('item_photos')
    # ### end Alembic commands ###
