"""price checks

Revision ID: 59de5a1c65af
Revises: c7e8b044f445
Create Date: 2026-09-27 21:02:17.452734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59de5a1c65af'
down_revision: Union[str, Sequence[str], None] = 'c7e8b044f445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_price_checks_catalog_num_catalog_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_checks')),
    sa.UniqueConstraint('user_id', 'catalog_num', name='uq_price_checks_user_num')
    )
    with op.batch_alter_table('price_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_checks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_checks_user_id'))

    op.drop_table('price_checks')
    # ### end Alembic commands ###
