"""kategorie a ulozene pohlady

Revision ID: 6192e629599d
Revises: 57764f8fc05e
Create Date: 2026-09-26 14:47:39.982878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6192e629599d'
down_revision: Union[str, Sequence[str], None] = '57764f8fc05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_id', 'name', name='user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('ix_categories_user_id', ['user_id'], unique=False)

    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_views_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views'))
    )
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.create_index('ix_saved_views_user_id', ['user_id'], unique=False)

    op.create_table('category_items',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_category_items_catalog_num_catalog_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_items_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'catalog_num', name=op.f('pk_category_items'))
    )
    # ### end Alembic commands ###

    # Hotová kategória „Formula 1“ pre existujúcich používateľov. F1 sety sa
    # naprieč témami volajú „… F1 …“ (McLaren F1 Team MCL38 Race Car), takže
    # stačí slovo F1 v názve. Samotné „Ferrari“ by chytilo aj bežné autá.
    conn = op.get_bind()
    users = conn.execute(sa.text("SELECT id FROM users")).fetchall()
    for (user_id,) in users:
        conn.execute(
            sa.text(
                "INSERT INTO categories (user_id, name, color, rules, sort_order, created_at) "
                "VALUES (:user_id, 'Formula 1', 'red', :rules, 0, CURRENT_TIMESTAMP)"
            ),
            {
                "user_id": user_id,
                "rules": '[{"field": "name", "op": "word", "value": "F1"}]',
            },
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_items')
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_views_user_id')

    op.drop_table('saved_views')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('ix_categories_user_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
