"""pociatocna schema

Revision ID: 9a38f007d771
Revises: 
Create Date: 2026-09-15 14:24:56.014361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a38f007d771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_num', sa.String(length=64), nullable=True),
    sa.Column('series_size', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('num_minifigs', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('rrp_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.Integer(), nullable=True),
    sa.Column('bricklink_no', sa.String(length=64), nullable=True),
    sa.Column('bricklink_type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_num'], ['catalog_items.catalog_num'], name=op.f('fk_catalog_items_parent_num_catalog_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('catalog_num', name=op.f('pk_catalog_items'))
    )
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.create_index('ix_catalog_items_kind', ['kind'], unique=False)
        batch_op.create_index('ix_catalog_items_parent_num', ['parent_num'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('price_variant', sa.String(length=16), nullable=True),
    sa.Column('unidentified', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('purchase_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_place', sa.String(length=160), nullable=True),
    sa.Column('sold_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sold_via', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('manual_market_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_collection_items_catalog_num_catalog_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collection_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items'))
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_location'), ['location'], unique=False)
        batch_op.create_index('ix_collection_items_user_catalog', ['user_id', 'catalog_num'], unique=False)
        batch_op.create_index('ix_collection_items_user_status', ['user_id', 'status'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('bricklink_type', sa.String(length=16), nullable=False),
    sa.Column('condition', sa.String(length=1), nullable=False),
    sa.Column('guide_type', sa.String(length=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_price_snapshots_catalog_num_catalog_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_snapshots'))
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_price_snapshots_lookup', ['catalog_num', 'bricklink_type', 'condition', 'guide_type', 'captured_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_refresh_tokens_user_id', ['user_id'], unique=False)

    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('show_values', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links'))
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_token'), ['token'], unique=True)
        batch_op.create_index('ix_share_links_user_id', ['user_id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_num', sa.String(length=64), nullable=False),
    sa.Column('target_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_num'], ['catalog_items.catalog_num'], name=op.f('fk_wishlist_items_catalog_num_catalog_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlist_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_items')),
    sa.UniqueConstraint('user_id', 'catalog_num', name='user_catalog')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_items')
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index('ix_share_links_user_id')
        batch_op.drop_index(batch_op.f('ix_share_links_token'))

    op.drop_table('share_links')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_id')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_price_snapshots_lookup')

    op.drop_table('price_snapshots')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_items_user_status')
        batch_op.drop_index('ix_collection_items_user_catalog')
        batch_op.drop_index(batch_op.f('ix_collection_items_location'))

    op.drop_table('collection_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_items_parent_num')
        batch_op.drop_index('ix_catalog_items_kind')

    op.drop_table('catalog_items')
    # ### end Alembic commands ###
