"""zasady sukromia

Revision ID: 9ea3442a1685
Revises: 155aeaebee97
Create Date: 2026-09-28 08:30:24.359364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea3442a1685'
down_revision: Union[str, Sequence[str], None] = '155aeaebee97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('privacy_version', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('privacy_version')
        batch_op.drop_column('privacy_accepted_at')

    # ### end Alembic commands ###
