"""historia volani api

Revision ID: 9eb0f09a029d
Revises: 41f471e813d2
Create Date: 2026-09-26 22:09:51.392552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb0f09a029d'
down_revision: Union[str, Sequence[str], None] = '41f471e813d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_calls_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_calls'))
    )
    with op.batch_alter_table('api_calls', schema=None) as batch_op:
        batch_op.create_index('ix_api_calls_at', ['at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_api_calls_at')

    op.drop_table('api_calls')
    # ### end Alembic commands ###
