"""hromadny import

Revision ID: 9fba0fa5a3c1
Revises: b1c263268a3e
Create Date: 2026-09-27 08:58:30.225980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fba0fa5a3c1'
down_revision: Union[str, Sequence[str], None] = 'b1c263268a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('ignored_columns', sa.JSON(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('removed_wishes', sa.JSON(), nullable=False),
    sa.Column('pieces_created', sa.Integer(), nullable=False),
    sa.Column('wishes_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_batches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_collection_items_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_collection_items_import_batch_id_import_batches'), 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_wishlist_items_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_wishlist_items_import_batch_id_import_batches'), 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_wishlist_items_import_batch_id_import_batches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wishlist_items_import_batch_id'))
        batch_op.drop_column('import_batch_id')

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_items_import_batch_id_import_batches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_collection_items_import_batch_id'))
        batch_op.drop_column('import_batch_id')

    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_user_id'))

    op.drop_table('import_batches')
    # ### end Alembic commands ###
