"""pravidla stahovania

Revision ID: a9263d1222ba
Revises: 9fba0fa5a3c1
Create Date: 2026-09-27 13:59:41.071802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9263d1222ba'
down_revision: Union[str, Sequence[str], None] = '9fba0fa5a3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fetch_settings', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fetch_settings')

    # ### end Alembic commands ###
