"""zberatelske serie

Revision ID: abd935c09366
Revises: 6192e629599d
Create Date: 2026-09-26 15:46:43.986934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd935c09366'
down_revision: Union[str, Sequence[str], None] = '6192e629599d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmf_series',
    sa.Column('theme_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('series_num', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('theme_id', name=op.f('pk_cmf_series'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmf_series')
    # ### end Alembic commands ###
