"""index inflacie

Revision ID: b1c263268a3e
Revises: 9eb0f09a029d
Create Date: 2026-09-26 22:36:03.183382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c263268a3e'
down_revision: Union[str, Sequence[str], None] = '9eb0f09a029d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inflation_index',
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('month', name=op.f('pk_inflation_index'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inflation_index')
    # ### end Alembic commands ###
