"""odhad a rast hodnoty

Revision ID: c30e390ab49a
Revises: f38093ed2cae
Create Date: 2026-09-26 11:50:29.858265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30e390ab49a'
down_revision: Union[str, Sequence[str], None] = 'f38093ed2cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_2y_eur', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('forecast_5y_eur', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('growth_12m_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('growth_last_year_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_column('growth_last_year_pct')
        batch_op.drop_column('growth_12m_pct')
        batch_op.drop_column('forecast_5y_eur')
        batch_op.drop_column('forecast_2y_eur')

    # ### end Alembic commands ###
