"""doplnena kupna cena a neuspesne kody

Revision ID: c6ca75a14f1e
Revises: a9263d1222ba
Create Date: 2026-09-27 15:37:55.040450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ca75a14f1e'
down_revision: Union[str, Sequence[str], None] = 'a9263d1222ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_misses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('product_title', sa.String(length=300), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_barcode_misses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barcode_misses')),
    sa.UniqueConstraint('user_id', 'ean', name='uq_barcode_misses_user_ean')
    )
    with op.batch_alter_table('barcode_misses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barcode_misses_ean'), ['ean'], unique=False)

    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price_auto', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_column('purchase_price_auto')

    with op.batch_alter_table('barcode_misses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barcode_misses_ean'))

    op.drop_table('barcode_misses')
    # ### end Alembic commands ###
