"""vyber setov v odkaze

Revision ID: c7e8b044f445
Revises: ac83f3437ebc
Create Date: 2026-09-27 20:03:37.213516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e8b044f445'
down_revision: Union[str, Sequence[str], None] = 'ac83f3437ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_nums', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_column('catalog_nums')

    # ### end Alembic commands ###
