"""brickset images

Revision ID: f210297cdb24
Revises: 59de5a1c65af
Create Date: 2026-09-27 21:46:58.907222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f210297cdb24'
down_revision: Union[str, Sequence[str], None] = '59de5a1c65af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brickset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bs_image_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bs_images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_items', schema=None) as batch_op:
        batch_op.drop_column('bs_images')
        batch_op.drop_column('bs_image_count')
        batch_op.drop_column('brickset_id')

    # ### end Alembic commands ###
