"""vlastne kluce pri ucte

Revision ID: f38093ed2cae
Revises: b1c4a7e20f11
Create Date: 2026-09-15 19:41:07.428506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38093ed2cae'
down_revision: Union[str, Sequence[str], None] = 'b1c4a7e20f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rebrickable_key_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('brickset_key_enc', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('brickeconomy_key_enc', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('brickeconomy_key_enc')
        batch_op.drop_column('brickset_key_enc')
        batch_op.drop_column('rebrickable_key_enc')

    # ### end Alembic commands ###
